version: '3'
services:
  influxdb-cloud:
    image: influxdb:latest
    container_name: influxdb-cloud
    ports:
      - "8087:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=alm-org
      - DOCKER_INFLUXDB_INIT_BUCKET=alm-sensors
      - DOCKER_INFLUXDB_INIT_RETENTION=168h
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=alm_token_cloud
    restart: unless-stopped

persister_mqtt_influxdb:
    build: .
    container_name: persister_mqtt_influxdb
    depends_on:
      - influxdb-cloud
    links:
      - influxdb-cloud
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: ["./wait-for-it.sh", "influxdb-cloud:8087", "--", "python", "data_persister.py"]
    environment:
      - INFLUXDB_URL=http://influxdb-cloud:8087
      - INFLUXDB_TOKEN=alm_token_cloud
      - INFLUXDB_ORG=alm-org
      - INFLUXDB_BUCKET=alm-sensors
    restart: unless-stopped