version: '3.8'

services:
  influxdbcloud:
    image: influxdb:2.7.10
    container_name: influxdbcloud
    ports:
      - "8087:8086"
    environment:
      # - INFLUXDB_INIT_MODE=setup
      # - INFLUXDB_DB=
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=adminpassword
      # - INFLUXDB_HTTP_AUTH_ENABLED=true
      # - INFLUXDB_BUCKET=alm-sensors
      # - INFLUXDB_ORG=alm-org
      # - INFLUXDB_TOKEN=alm_gateway_local_token
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=alm-org
      - DOCKER_INFLUXDB_INIT_BUCKET=alm-sensors
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=alm_cloud_local_token
    # volumes:
    #   - ./influxdb/data:/var/lib/influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    # networks:
    #   - telegraf_network

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdbcloud
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    # networks:
    #   - telegraf_network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdbcloud
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    # networks:
#       - telegraf_network

# networks:
#   telegraf_network:
#     driver: bridge

  create_api_key:
    image: curlimages/curl:latest
    container_name: create_api_key
    depends_on:
      - influxdbcloud
      - grafana
    volumes:
      - ./create_api_key.sh:/create_api_key.sh
    entrypoint: ["sh", "/create_api_key.sh"]
    restart: "no"

volumes:
  influxdb_data: