version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  ev-data-filterer:
    image: ev-data-filterer
    container_name: ev-data-filterer
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER_ADDRESS=mqtt
      - MQTT_BROKER_PORT=1883

  heartrate-sensor-mqtt:
    image: heartrate-sensor-mqtt
    container_name: heartrate-sensor-mqtt
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER_ADDRESS=mqtt
      - MQTT_BROKER_PORT=1883